# vim: sw=2

name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:

  package-arch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["debian:sid", "debian:bookworm"]
    container:
      image: ${{ matrix.image }}
      # IPC_OWNER is needed for shmget IPC_CREAT
      # SYS_ADMIN is needed for shmctl IPC_SET
      options: --cpus=2 --cap-add=IPC_OWNER --cap-add=SYS_ADMIN
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Install pre-dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set -e
        set -x
        apt-get --quiet update
        apt-get --yes --quiet install eatmydata
        # Install stuff needed to check out the linuxcnc repo and turn it into a debian source package.
        eatmydata apt-get --yes --quiet install --no-install-suggests git lsb-release python3 devscripts

    - uses: actions/checkout@v3
      with:
        # "fetch-depth: 0" fetches all of history, this is needed by
        # our build system to determine the version from tags
        fetch-depth: 0

    - name: Add linuxcnc.org deb archive
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        case "${{matrix.image}}" in
            debian:sid|debian:bookworm)
                exit 0
                ;;
            *)
                ;;
        esac
        set -e
        set -x
        eatmydata apt-get --yes --quiet install --no-install-recommends gpg software-properties-common
        eatmydata gpg --homedir="${PWD}/gnupg" --output /etc/apt/trusted.gpg.d/linuxcnc-deb-archive.gpg --export 3CB9FD148F374FEF
        DIST=$(echo ${{matrix.image}} | cut -d : -f 2)
        eatmydata add-apt-repository "deb http://linuxcnc.org $DIST base"
        eatmydata apt-get --quiet update

    - name: Build architecture-specific Debian packages
      env:
        DEBEMAIL: emc-developers@lists.sourceforge.net
        DEBFULLNAME: LinuxCNC Github CI Robot
        DEBIAN_FRONTEND: noninteractive
      run: |
        set -e
        set -x
        eatmydata git config --global --add safe.directory "${PWD}"
        eatmydata debian/configure
        eatmydata debian/update-dch-from-git
        eatmydata scripts/get-version-from-git | sed -re 's/^v(.*)$/\1/' >| VERSION; cat VERSION
        eatmydata git diff
        eatmydata apt-get --yes --quiet build-dep --arch-only .
        eatmydata debuild -us -uc --build=any
    - name: Test debian packages
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set -e
        set -x
        eatmydata apt-get --yes --quiet install ../*.deb
        eatmydata apt-get --yes --quiet install sudo # some tests run sudo...
        eatmydata adduser --disabled-password --gecos "" testrunner
        eatmydata passwd -d testrunner
        eatmydata adduser testrunner sudo
        chmod 0777 $(find tests/ -type d) # make test dirs world-writable for the testrunner
        su -c "eatmydata ./scripts/runtests -v -p ./tests" testrunner
